# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "bluebird-3.5.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.5.0.tgz";
        sha1 = "791420d7f551eea2897453a8a77653f96606d67c";
      };
    };
    "child-process-promise-2.2.1" = {
      name = "child-process-promise";
      packageName = "child-process-promise";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/child-process-promise/-/child-process-promise-2.2.1.tgz";
        sha1 = "4730a11ef610fad450b8f223c79d31d7bdad8074";
      };
    };
    "request-2.81.0" = {
      name = "request";
      packageName = "request";
      version = "2.81.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.81.0.tgz";
        sha1 = "c6928946a0e06c5f8d6f8a9333469ffda46298a0";
      };
    };
    "cheerio-1.0.0-rc.2" = {
      name = "cheerio";
      packageName = "cheerio";
      version = "1.0.0-rc.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cheerio/-/cheerio-1.0.0-rc.2.tgz";
        sha1 = "4b9f53a81b27e4d5dac31c0ffd0cfa03cc6830db";
      };
    };
    "fs-extra-4.0.1" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-4.0.1.tgz";
        sha1 = "7fc0c6c8957f983f57f306a24e5b9ddd8d0dd880";
      };
    };
    "google-play-scraper-3.3.1" = {
      name = "google-play-scraper";
      packageName = "google-play-scraper";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/google-play-scraper/-/google-play-scraper-3.3.1.tgz";
        sha1 = "309a2a725d1308c9cae70068422fc2c8200453a2";
      };
    };
    "pg-6.4.2" = {
      name = "pg";
      packageName = "pg";
      version = "6.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg/-/pg-6.4.2.tgz";
        sha1 = "c364011060eac7a507a2ae063eb857ece910e27f";
      };
    };
    "cross-spawn-4.0.2" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-4.0.2.tgz";
        sha1 = "7b9247621c23adfdd3856004a823cbe397424d41";
      };
    };
    "node-version-1.1.0" = {
      name = "node-version";
      packageName = "node-version";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-version/-/node-version-1.1.0.tgz";
        sha1 = "f437d7ba407e65e2c4eaef8887b1718ba523d4f0";
      };
    };
    "promise-polyfill-6.0.2" = {
      name = "promise-polyfill";
      packageName = "promise-polyfill";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise-polyfill/-/promise-polyfill-6.0.2.tgz";
        sha1 = "d9c86d3dc4dc2df9016e88946defd69b49b41162";
      };
    };
    "lru-cache-4.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.1.tgz";
        sha1 = "622e32e82488b49279114a4f9ecf45e7cd6bba55";
      };
    };
    "which-1.3.0" = {
      name = "which";
      packageName = "which";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.0.tgz";
        sha1 = "ff04bdfc010ee547d780bec38e1ac1c2777d253a";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.1.4" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.1.4.tgz";
        sha1 = "33c183acf193276ecaa98143a69e94bfee1750d1";
      };
    };
    "har-validator-4.2.1" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-4.2.1.tgz";
        sha1 = "33481d0f1bbff600dd203d75812a6a5fba002e2a";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.16" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.16.tgz";
        sha1 = "2b858a52e5ecd516db897ac2be87487830698e23";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "performance-now-0.2.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-0.2.0.tgz";
        sha1 = "33ef30c5c77d4ea21c5a53869d91b56d8f2555e5";
      };
    };
    "qs-6.4.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.4.0.tgz";
        sha1 = "13e26d28ad6b0ffaa91312cd3bf708ed351e7233";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha1 = "893312af69b2123def71f57889001671eeb2c853";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.2" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.2.tgz";
        sha1 = "f081f76e4c85720e6c37a5faced737150d84072a";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "uuid-3.1.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz";
        sha1 = "3dd3d3e790abc24d7b0d3a034ffababe28ebbc04";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "ajv-4.11.8" = {
      name = "ajv";
      packageName = "ajv";
      version = "4.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-4.11.8.tgz";
        sha1 = "82ffb02b29e662ae53bdc20af15947706739c536";
      };
    };
    "har-schema-1.0.5" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-1.0.5.tgz";
        sha1 = "d263135f43307c02c602afc8fe95970c0151369e";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "sshpk-1.13.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz";
        sha1 = "512df6da6287144316dc4c18fe1cf1d940739be3";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "mime-db-1.29.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.29.0.tgz";
        sha1 = "48d26d235589651704ac5916ca06001914266878";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "css-select-1.2.0" = {
      name = "css-select";
      packageName = "css-select";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-1.2.0.tgz";
        sha1 = "2b3a110539c5355f1cd8d314623e870b121ec858";
      };
    };
    "dom-serializer-0.1.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.0.tgz";
        sha1 = "073c697546ce0780ce23be4a28e293e40bc30c82";
      };
    };
    "entities-1.1.1" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.1.tgz";
        sha1 = "6e5c2d0a5621b5dadaecef80b90edfb5cd7772f0";
      };
    };
    "htmlparser2-3.9.2" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.9.2.tgz";
        sha1 = "1bdf87acca0f3f9e53fa4fcceb0f4b4cbb00b338";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "parse5-3.0.2" = {
      name = "parse5";
      packageName = "parse5";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5/-/parse5-3.0.2.tgz";
        sha1 = "05eff57f0ef4577fb144a79f8b9a967a6cc44510";
      };
    };
    "css-what-2.1.0" = {
      name = "css-what";
      packageName = "css-what";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-2.1.0.tgz";
        sha1 = "9467d032c38cfaefb9f2d79501253062f87fa1bd";
      };
    };
    "domutils-1.5.1" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.5.1.tgz";
        sha1 = "dcd8488a26f563d61079e48c9f7b7e32373682cf";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha1 = "68dff5fbe60c51eb37725ea9e3ed310dcc1e776e";
      };
    };
    "nth-check-1.0.1" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-1.0.1.tgz";
        sha1 = "9929acdf628fc2c41098deab82ac580cf149aae4";
      };
    };
    "domelementtype-1.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz";
        sha1 = "b17aed82e8ab59e52dd9c19b1756e0fc187204c2";
      };
    };
    "domelementtype-1.1.3" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz";
        sha1 = "bd28773e2642881aec51544924299c5cd822185b";
      };
    };
    "domhandler-2.4.1" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.4.1.tgz";
        sha1 = "892e47000a99be55bbf3774ffea0561d8879c259";
      };
    };
    "domutils-1.6.2" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.6.2.tgz";
        sha1 = "1958cc0b4c9426e9ed367fb1c8e854891b0fa3ff";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "readable-stream-2.3.3" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.3.tgz";
        sha1 = "368f2512d79f9d46fdfc71349ae7878bbc1eb95c";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-1.0.3" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz";
        sha1 = "0fc67d7c141825de94282dd536bec6b9bce860ab";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "@types/node-6.0.87" = {
      name = "@types/node";
      packageName = "@types/node";
      version = "6.0.87";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-6.0.87.tgz";
        sha1 = "5ab5774f8351a33a935099fa6be850aa0b0ad564";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "jsonfile-3.0.1" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-3.0.1.tgz";
        sha1 = "a5ecc6f65f53f662c4415c7675a0331d0992ec66";
      };
    };
    "universalify-0.1.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.1.tgz";
        sha1 = "fa71badd4437af4c148841e3b3b165f9e9e590b7";
      };
    };
    "cheerio-0.20.0" = {
      name = "cheerio";
      packageName = "cheerio";
      version = "0.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cheerio/-/cheerio-0.20.0.tgz";
        sha1 = "5c710f2bab95653272842ba01c6ea61b3545ec35";
      };
    };
    "debug-2.6.8" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.8.tgz";
        sha1 = "e731531ca2ede27d188222427da17821d68ff4fc";
      };
    };
    "memoizee-0.3.10" = {
      name = "memoizee";
      packageName = "memoizee";
      version = "0.3.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/memoizee/-/memoizee-0.3.10.tgz";
        sha1 = "4eca0d8aed39ec9d017f4c5c2f2f6432f42e5c8f";
      };
    };
    "ramda-0.21.0" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.21.0.tgz";
        sha1 = "a001abedb3ff61077d4ff1d577d44de77e8d0a35";
      };
    };
    "throttled-request-0.1.1" = {
      name = "throttled-request";
      packageName = "throttled-request";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/throttled-request/-/throttled-request-0.1.1.tgz";
        sha1 = "4146b70b77a5aeca33c46332cf13eb9c791e971b";
      };
    };
    "htmlparser2-3.8.3" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz";
        sha1 = "996c28b191516a8be86501a7d79757e5c70c1068";
      };
    };
    "jsdom-7.2.2" = {
      name = "jsdom";
      packageName = "jsdom";
      version = "7.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsdom/-/jsdom-7.2.2.tgz";
        sha1 = "40b402770c2bda23469096bee91ab675e3b1fc6e";
      };
    };
    "domhandler-2.3.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.3.0.tgz";
        sha1 = "2de59a0822d5027fabff6f032c2b25a2a8abe738";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "entities-1.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.0.0.tgz";
        sha1 = "b2987aa3821347fcde642b24fdfc9e4fb712bf26";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "abab-1.0.3" = {
      name = "abab";
      packageName = "abab";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/abab/-/abab-1.0.3.tgz";
        sha1 = "b81de5f7274ec4e756d797cd834f303642724e5d";
      };
    };
    "acorn-2.7.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-2.7.0.tgz";
        sha1 = "ab6e7d9d886aaca8b085bc3312b79a198433f0e7";
      };
    };
    "acorn-globals-1.0.9" = {
      name = "acorn-globals";
      packageName = "acorn-globals";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-globals/-/acorn-globals-1.0.9.tgz";
        sha1 = "55bb5e98691507b74579d0513413217c380c54cf";
      };
    };
    "cssom-0.3.2" = {
      name = "cssom";
      packageName = "cssom";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssom/-/cssom-0.3.2.tgz";
        sha1 = "b8036170c79f07a90ff2f16e22284027a243848b";
      };
    };
    "cssstyle-0.2.37" = {
      name = "cssstyle";
      packageName = "cssstyle";
      version = "0.2.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssstyle/-/cssstyle-0.2.37.tgz";
        sha1 = "541097234cb2513c83ceed3acddc27ff27987d54";
      };
    };
    "escodegen-1.8.1" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.8.1.tgz";
        sha1 = "5a5b53af4693110bebb0867aa3430dd3b70a1018";
      };
    };
    "nwmatcher-1.4.1" = {
      name = "nwmatcher";
      packageName = "nwmatcher";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nwmatcher/-/nwmatcher-1.4.1.tgz";
        sha1 = "7ae9b07b0ea804db7e25f05cb5fe4097d4e4949f";
      };
    };
    "parse5-1.5.1" = {
      name = "parse5";
      packageName = "parse5";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5/-/parse5-1.5.1.tgz";
        sha1 = "9b7f3b0de32be78dc2401b17573ccaf0f6f59d94";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha1 = "2816234e2378bddc4e5354fab5caa895df7100d9";
      };
    };
    "symbol-tree-3.2.2" = {
      name = "symbol-tree";
      packageName = "symbol-tree";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-tree/-/symbol-tree-3.2.2.tgz";
        sha1 = "ae27db38f660a7ae2e1c3b7d1bc290819b8519e6";
      };
    };
    "webidl-conversions-2.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-2.0.1.tgz";
        sha1 = "3bf8258f7d318c7443c36f2e169402a1a6703506";
      };
    };
    "whatwg-url-compat-0.6.5" = {
      name = "whatwg-url-compat";
      packageName = "whatwg-url-compat";
      version = "0.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url-compat/-/whatwg-url-compat-0.6.5.tgz";
        sha1 = "00898111af689bb097541cd5a45ca6c8798445bf";
      };
    };
    "xml-name-validator-2.0.1" = {
      name = "xml-name-validator";
      packageName = "xml-name-validator";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml-name-validator/-/xml-name-validator-2.0.1.tgz";
        sha1 = "4d8b8f1eccd3419aa362061becef515e1e559635";
      };
    };
    "estraverse-1.9.3" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-1.9.3.tgz";
        sha1 = "af67f2dc922582415950926091a4005d29c9bb44";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "source-map-0.2.0" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.2.0.tgz";
        sha1 = "dab73fbcfc2ba819b4de03bd6f6eaa48164b3f9d";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha1 = "8184fd347dac9cdc185992f3a6622e14b9d9ab6a";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "d-0.1.1" = {
      name = "d";
      packageName = "d";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-0.1.1.tgz";
        sha1 = "da184c535d18d8ee7ba2aa229b914009fae11309";
      };
    };
    "es5-ext-0.10.29" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.29.tgz";
        sha1 = "768eb2dfc4957bcf35fa0568f193ab71ede53fd8";
      };
    };
    "es6-weak-map-0.1.4" = {
      name = "es6-weak-map";
      packageName = "es6-weak-map";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-weak-map/-/es6-weak-map-0.1.4.tgz";
        sha1 = "706cef9e99aa236ba7766c239c8b9e286ea7d228";
      };
    };
    "event-emitter-0.3.5" = {
      name = "event-emitter";
      packageName = "event-emitter";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-emitter/-/event-emitter-0.3.5.tgz";
        sha1 = "df8c69eef1647923c7157b9ce83840610b02cc39";
      };
    };
    "lru-queue-0.1.0" = {
      name = "lru-queue";
      packageName = "lru-queue";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-queue/-/lru-queue-0.1.0.tgz";
        sha1 = "2738bd9f0d3cf4f84490c5736c48699ac632cda3";
      };
    };
    "next-tick-0.2.2" = {
      name = "next-tick";
      packageName = "next-tick";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-tick/-/next-tick-0.2.2.tgz";
        sha1 = "75da4a927ee5887e39065880065b7336413b310d";
      };
    };
    "timers-ext-0.1.2" = {
      name = "timers-ext";
      packageName = "timers-ext";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-ext/-/timers-ext-0.1.2.tgz";
        sha1 = "61cc47a76c1abd3195f14527f978d58ae94c5204";
      };
    };
    "es6-iterator-2.0.1" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.1.tgz";
        sha1 = "8e319c9f0453bf575d374940a655920e59ca5512";
      };
    };
    "es6-symbol-3.1.1" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.1.tgz";
        sha1 = "bf00ef4fdab6ba1b46ecb7b629b4c7ed5715cc77";
      };
    };
    "d-1.0.0" = {
      name = "d";
      packageName = "d";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-1.0.0.tgz";
        sha1 = "754bb5bfe55451da69a58b94d45f4c5b0462d58f";
      };
    };
    "es6-iterator-0.1.3" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-0.1.3.tgz";
        sha1 = "d6f58b8c4fc413c249b4baa19768f8e4d7c8944e";
      };
    };
    "es6-symbol-2.0.1" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-2.0.1.tgz";
        sha1 = "761b5c67cfd4f1d18afb234f691d678682cb3bf3";
      };
    };
    "next-tick-1.0.0" = {
      name = "next-tick";
      packageName = "next-tick";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-tick/-/next-tick-1.0.0.tgz";
        sha1 = "ca86d1fe8828169b0120208e3dc8424b9db8342c";
      };
    };
    "buffer-writer-1.0.1" = {
      name = "buffer-writer";
      packageName = "buffer-writer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-writer/-/buffer-writer-1.0.1.tgz";
        sha1 = "22a936901e3029afcd7547eb4487ceb697a3bf08";
      };
    };
    "packet-reader-0.3.1" = {
      name = "packet-reader";
      packageName = "packet-reader";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/packet-reader/-/packet-reader-0.3.1.tgz";
        sha1 = "cd62e60af8d7fea8a705ec4ff990871c46871f27";
      };
    };
    "js-string-escape-1.0.1" = {
      name = "js-string-escape";
      packageName = "js-string-escape";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-string-escape/-/js-string-escape-1.0.1.tgz";
        sha1 = "e2625badbc0d67c7533e9edc1068c587ae4137ef";
      };
    };
    "pg-connection-string-0.1.3" = {
      name = "pg-connection-string";
      packageName = "pg-connection-string";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-connection-string/-/pg-connection-string-0.1.3.tgz";
        sha1 = "da1847b20940e42ee1492beaf65d49d91b245df7";
      };
    };
    "pg-pool-1.8.0" = {
      name = "pg-pool";
      packageName = "pg-pool";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-pool/-/pg-pool-1.8.0.tgz";
        sha1 = "f7ec73824c37a03f076f51bfdf70e340147c4f37";
      };
    };
    "pg-types-1.12.1" = {
      name = "pg-types";
      packageName = "pg-types";
      version = "1.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-types/-/pg-types-1.12.1.tgz";
        sha1 = "d64087e3903b58ffaad279e7595c52208a14c3d2";
      };
    };
    "pgpass-1.0.2" = {
      name = "pgpass";
      packageName = "pgpass";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pgpass/-/pgpass-1.0.2.tgz";
        sha1 = "2a7bb41b6065b67907e91da1b07c1847c877b306";
      };
    };
    "semver-4.3.2" = {
      name = "semver";
      packageName = "semver";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-4.3.2.tgz";
        sha1 = "c7a07158a80bedd052355b770d82d6640f803be7";
      };
    };
    "generic-pool-2.4.3" = {
      name = "generic-pool";
      packageName = "generic-pool";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/generic-pool/-/generic-pool-2.4.3.tgz";
        sha1 = "780c36f69dfad05a5a045dd37be7adca11a4f6ff";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "postgres-array-1.0.2" = {
      name = "postgres-array";
      packageName = "postgres-array";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-array/-/postgres-array-1.0.2.tgz";
        sha1 = "8e0b32eb03bf77a5c0a7851e0441c169a256a238";
      };
    };
    "postgres-bytea-1.0.0" = {
      name = "postgres-bytea";
      packageName = "postgres-bytea";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-bytea/-/postgres-bytea-1.0.0.tgz";
        sha1 = "027b533c0aa890e26d172d47cf9ccecc521acd35";
      };
    };
    "postgres-date-1.0.3" = {
      name = "postgres-date";
      packageName = "postgres-date";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-date/-/postgres-date-1.0.3.tgz";
        sha1 = "e2d89702efdb258ff9d9cee0fe91bd06975257a8";
      };
    };
    "postgres-interval-1.1.1" = {
      name = "postgres-interval";
      packageName = "postgres-interval";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-interval/-/postgres-interval-1.1.1.tgz";
        sha1 = "acdb0f897b4b1c6e496d9d4e0a853e1c428f06f0";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "split-1.0.1" = {
      name = "split";
      packageName = "split";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-1.0.1.tgz";
        sha1 = "605bd9be303aa59fb35f9229fbea0ddec9ea07d9";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
  };
  args = {
    name = "scrapetools";
    packageName = "scrapetools";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."bluebird-3.5.0"
      (sources."child-process-promise-2.2.1" // {
        dependencies = [
          (sources."cross-spawn-4.0.2" // {
            dependencies = [
              (sources."lru-cache-4.1.1" // {
                dependencies = [
                  sources."pseudomap-1.0.2"
                  sources."yallist-2.1.2"
                ];
              })
              (sources."which-1.3.0" // {
                dependencies = [
                  sources."isexe-2.0.0"
                ];
              })
            ];
          })
          sources."node-version-1.1.0"
          sources."promise-polyfill-6.0.2"
        ];
      })
      (sources."request-2.81.0" // {
        dependencies = [
          sources."aws-sign2-0.6.0"
          sources."aws4-1.6.0"
          sources."caseless-0.12.0"
          (sources."combined-stream-1.0.5" // {
            dependencies = [
              sources."delayed-stream-1.0.0"
            ];
          })
          sources."extend-3.0.1"
          sources."forever-agent-0.6.1"
          (sources."form-data-2.1.4" // {
            dependencies = [
              sources."asynckit-0.4.0"
            ];
          })
          (sources."har-validator-4.2.1" // {
            dependencies = [
              (sources."ajv-4.11.8" // {
                dependencies = [
                  sources."co-4.6.0"
                  (sources."json-stable-stringify-1.0.1" // {
                    dependencies = [
                      sources."jsonify-0.0.0"
                    ];
                  })
                ];
              })
              sources."har-schema-1.0.5"
            ];
          })
          (sources."hawk-3.1.3" // {
            dependencies = [
              sources."hoek-2.16.3"
              sources."boom-2.10.1"
              sources."cryptiles-2.0.5"
              sources."sntp-1.0.9"
            ];
          })
          (sources."http-signature-1.1.1" // {
            dependencies = [
              sources."assert-plus-0.2.0"
              (sources."jsprim-1.4.1" // {
                dependencies = [
                  sources."assert-plus-1.0.0"
                  sources."extsprintf-1.3.0"
                  sources."json-schema-0.2.3"
                  (sources."verror-1.10.0" // {
                    dependencies = [
                      sources."core-util-is-1.0.2"
                    ];
                  })
                ];
              })
              (sources."sshpk-1.13.1" // {
                dependencies = [
                  sources."asn1-0.2.3"
                  sources."assert-plus-1.0.0"
                  sources."dashdash-1.14.1"
                  sources."getpass-0.1.7"
                  sources."jsbn-0.1.1"
                  sources."tweetnacl-0.14.5"
                  sources."ecc-jsbn-0.1.1"
                  sources."bcrypt-pbkdf-1.0.1"
                ];
              })
            ];
          })
          sources."is-typedarray-1.0.0"
          sources."isstream-0.1.2"
          sources."json-stringify-safe-5.0.1"
          (sources."mime-types-2.1.16" // {
            dependencies = [
              sources."mime-db-1.29.0"
            ];
          })
          sources."oauth-sign-0.8.2"
          sources."performance-now-0.2.0"
          sources."qs-6.4.0"
          sources."safe-buffer-5.1.1"
          sources."stringstream-0.0.5"
          (sources."tough-cookie-2.3.2" // {
            dependencies = [
              sources."punycode-1.4.1"
            ];
          })
          sources."tunnel-agent-0.6.0"
          sources."uuid-3.1.0"
        ];
      })
      (sources."cheerio-1.0.0-rc.2" // {
        dependencies = [
          (sources."css-select-1.2.0" // {
            dependencies = [
              sources."css-what-2.1.0"
              (sources."domutils-1.5.1" // {
                dependencies = [
                  sources."domelementtype-1.3.0"
                ];
              })
              sources."boolbase-1.0.0"
              sources."nth-check-1.0.1"
            ];
          })
          (sources."dom-serializer-0.1.0" // {
            dependencies = [
              sources."domelementtype-1.1.3"
            ];
          })
          sources."entities-1.1.1"
          (sources."htmlparser2-3.9.2" // {
            dependencies = [
              sources."domelementtype-1.3.0"
              sources."domhandler-2.4.1"
              sources."domutils-1.6.2"
              sources."inherits-2.0.3"
              (sources."readable-stream-2.3.3" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-1.0.7"
                  sources."safe-buffer-5.1.1"
                  sources."string_decoder-1.0.3"
                  sources."util-deprecate-1.0.2"
                ];
              })
            ];
          })
          sources."lodash-4.17.4"
          (sources."parse5-3.0.2" // {
            dependencies = [
              sources."@types/node-6.0.87"
            ];
          })
        ];
      })
      (sources."fs-extra-4.0.1" // {
        dependencies = [
          sources."graceful-fs-4.1.11"
          sources."jsonfile-3.0.1"
          sources."universalify-0.1.1"
        ];
      })
      (sources."google-play-scraper-3.3.1" // {
        dependencies = [
          (sources."cheerio-0.20.0" // {
            dependencies = [
              (sources."css-select-1.2.0" // {
                dependencies = [
                  sources."css-what-2.1.0"
                  (sources."domutils-1.5.1" // {
                    dependencies = [
                      sources."domelementtype-1.3.0"
                    ];
                  })
                  sources."boolbase-1.0.0"
                  sources."nth-check-1.0.1"
                ];
              })
              sources."entities-1.1.1"
              (sources."htmlparser2-3.8.3" // {
                dependencies = [
                  sources."domhandler-2.3.0"
                  sources."domutils-1.5.1"
                  sources."domelementtype-1.3.0"
                  (sources."readable-stream-1.1.14" // {
                    dependencies = [
                      sources."core-util-is-1.0.2"
                      sources."isarray-0.0.1"
                      sources."string_decoder-0.10.31"
                      sources."inherits-2.0.3"
                    ];
                  })
                  sources."entities-1.0.0"
                ];
              })
              (sources."dom-serializer-0.1.0" // {
                dependencies = [
                  sources."domelementtype-1.1.3"
                ];
              })
              sources."lodash-4.17.4"
              (sources."jsdom-7.2.2" // {
                dependencies = [
                  sources."abab-1.0.3"
                  sources."acorn-2.7.0"
                  sources."acorn-globals-1.0.9"
                  sources."cssom-0.3.2"
                  sources."cssstyle-0.2.37"
                  (sources."escodegen-1.8.1" // {
                    dependencies = [
                      sources."estraverse-1.9.3"
                      sources."esutils-2.0.2"
                      sources."esprima-2.7.3"
                      (sources."optionator-0.8.2" // {
                        dependencies = [
                          sources."prelude-ls-1.1.2"
                          sources."deep-is-0.1.3"
                          sources."wordwrap-1.0.0"
                          sources."type-check-0.3.2"
                          sources."levn-0.3.0"
                          sources."fast-levenshtein-2.0.6"
                        ];
                      })
                      (sources."source-map-0.2.0" // {
                        dependencies = [
                          sources."amdefine-1.0.1"
                        ];
                      })
                    ];
                  })
                  sources."nwmatcher-1.4.1"
                  sources."parse5-1.5.1"
                  sources."sax-1.2.4"
                  sources."symbol-tree-3.2.2"
                  (sources."tough-cookie-2.3.2" // {
                    dependencies = [
                      sources."punycode-1.4.1"
                    ];
                  })
                  sources."webidl-conversions-2.0.1"
                  (sources."whatwg-url-compat-0.6.5" // {
                    dependencies = [
                      sources."tr46-0.0.3"
                    ];
                  })
                  sources."xml-name-validator-2.0.1"
                ];
              })
            ];
          })
          (sources."debug-2.6.8" // {
            dependencies = [
              sources."ms-2.0.0"
            ];
          })
          (sources."memoizee-0.3.10" // {
            dependencies = [
              sources."d-0.1.1"
              (sources."es5-ext-0.10.29" // {
                dependencies = [
                  (sources."es6-iterator-2.0.1" // {
                    dependencies = [
                      sources."d-1.0.0"
                    ];
                  })
                  (sources."es6-symbol-3.1.1" // {
                    dependencies = [
                      sources."d-1.0.0"
                    ];
                  })
                ];
              })
              (sources."es6-weak-map-0.1.4" // {
                dependencies = [
                  sources."es6-iterator-0.1.3"
                  sources."es6-symbol-2.0.1"
                ];
              })
              (sources."event-emitter-0.3.5" // {
                dependencies = [
                  sources."d-1.0.0"
                ];
              })
              sources."lru-queue-0.1.0"
              sources."next-tick-0.2.2"
              (sources."timers-ext-0.1.2" // {
                dependencies = [
                  sources."next-tick-1.0.0"
                ];
              })
            ];
          })
          sources."ramda-0.21.0"
          sources."throttled-request-0.1.1"
        ];
      })
      (sources."pg-6.4.2" // {
        dependencies = [
          sources."buffer-writer-1.0.1"
          sources."packet-reader-0.3.1"
          sources."js-string-escape-1.0.1"
          sources."pg-connection-string-0.1.3"
          (sources."pg-pool-1.8.0" // {
            dependencies = [
              sources."generic-pool-2.4.3"
              sources."object-assign-4.1.0"
            ];
          })
          (sources."pg-types-1.12.1" // {
            dependencies = [
              sources."postgres-array-1.0.2"
              sources."postgres-bytea-1.0.0"
              sources."postgres-date-1.0.3"
              (sources."postgres-interval-1.1.1" // {
                dependencies = [
                  sources."xtend-4.0.1"
                ];
              })
            ];
          })
          (sources."pgpass-1.0.2" // {
            dependencies = [
              (sources."split-1.0.1" // {
                dependencies = [
                  sources."through-2.3.8"
                ];
              })
            ];
          })
          sources."semver-4.3.2"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "BSD";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}