package main

var mobTrackers = strmap(
	"Inmobi", "Mopub", "Facebook", "Chartboost",
	"Crashlytics", "Heyzap", "Applovin",
	"Unitytechnologies", "Vungle", "Fyber",
	"Millenialmedia", "Ironsource", "Tapjoy",
	"Flurry", "Google", "Bitstadium", "Presage",
	"Comscore", "Umeng", "Tencent", "Nexage",
	"Mixpanel", "Appboy", "Yandex", "Kochava",
	"Urbanairship", "Daum", "Milkman", "Playhaven",
	"Umeng", "Mail.Ru", "Newrelic", "Admob",
	"Moat", "Smaato", "Admarvel", "Appodeal",
	"Cauley", "Revmob", "Adbuddiz", "Igaworks",
	"Nativex", "Smartadserver", "Mobfox",
	"Pubnative", "Hyprmx", "Pingstart", "Tune",
	"Baidu", "Swrve", "Tnkfactory", "Appnext",
	"Tencent",
)

var webTrackers = strmap(
	"Google", "Doubleclick", "Facebook",
	"Cloudfront", "Scorecardresearch", "Appnexus",
	"Twitter", "Amazon", "Criteo", "Yahoo",
	"Oracle", "Quantcast", "Iponweb", "Adobe",
	"Openx", "Ghostery", "Rubicon", "Bluekai",
	"Cloudflare", "Liveramp", "The Nielsen Company",
	"Demdex", "Truste", "Newrelic",
	"Integral Ad Science", "Adsrvr", "Moatads",
	"Pubmatic", "Turn", "Indexchange",
	"Doubleverify", "Mathtag", "Chartbeat",
	"Optimizely", "Youtube", "Tapad", "Exelate",
	"Targus", "Lotame", "Sizmek", "Iasds",
	"Neustar", "Jquery", "Krxd", "Adroll",
	"Brightroll", "Audiencescience", "Bootstrap",
	"Rocketfuel", "Dataxu", "Tubemogul",
	"Microsoft", "Yandex", "Conversant",
	"Videology", "Flashtalking", "Akamai",
	"Adap.Tv", "Magnetic", "Dstillery", "Baidu",
	"Smartadserver", "Taboola", "H&R Block",
	"Tealium", "Convertro", "MSN", "Linkedin",
	"Mookie1", "Contextweb", "Liverail", "Yadro",
	"Bug", "Chango", "Conversant Llc", "Trueffect",
	"Signal-Privacy", "Crazy Egg", "Drawbridge Inc",
	"Sovrn", "Ovh", "Exponential", "Yieldoptimizer",
	"Spotxchange", "Owneriq", "Insightexpress",
	"Adform", "Automattic", "Disqus", "Outbrain",
	"Flipps", "Centromedia", "Ignitionone",
	"Skimlinks", "Simpli.Fi", "Wordpress",
	"Openx Technologies", "Ensighten",
	"Visual Website Optimizer", "Rhythmone",
	"Mixpanel", "Sonobi", "Hotjar", "Voicefive",
	"Gssprt", "At Internet", "Ml314", "Radiumone",
	"Parsely", "Improve Digital Bv", "Gumgum",
	"Amgdgt", "Effective Measure", "Pinterest",
	"Vk", "Adition", "Exoclick", "Ixi Corporation",
	"Nugg.Ad", "Umeng", "Alibaba", "Marketo",
	"Gskinner", "Gigya", "Tns", "Eq Works",
	"Cxense Asa", "Steelhouse", "Yieldlab",
	"33Across", "Mail.Ru", "Pingdom Ab",
	"Smart Adserver", "Brightcove", "Postrelease",
	"Adriver", "Pagefair", "Microad",
	"Marin Software", "Collective", "Trafficjunky",
	"Pixalate", "Demandbase", "Yieldbot",
	"Visualdna", "Ioam", "Signal", "Shopzilla",
	"Sharethrough", "Rambler", "Clicktale",
	"Sociomantic", "Datonics", "Run", "Myspace",
	"Taobao", "Adgear Technologies", "Sharethis",
	"Mybuys", "Stroeer Media",
	"The Mcgraw-Hill Companies", "Vizury", "Abc",
	"Dyn", "Longtail Ad Solutions", "Netseer",
	"Smaato", "The Adex Gmbh", "Adblade",
	"Mxptint", "Maxymiser", "Admeta", "Mcro",
	"Sourcepoint Technologies", "Yieldmanager",
	"Rfihub", "Bounce Exchange", "Wtp",
	"Convertmedia", "Rackspace Us", "Eyeview",
	"Qualtrics", "Intent Iq", "Stickyads.Tv",
	"Soasta", "Cedexis Inc", "Weborama",
	"Invite Media", "Histats", "Statcounter",
	"Paypal", "Bidr", "Springserve", "Yahoo",
	"Nexstar Broadcasting", "Triplelift",
	"Polar", "Adelphic Inc", "Deep Forest Media",
	"Cedexis", "Richrelevance", "Resonate",
	"Impact-Ad", "Jivox", "Mediade",
	"Liveperson", "Zedo", "Yabidos", "Adfox",
	"Fout", "Switch", "Navegg S.A.", "Adsnative",
	"Eyeota Limited", "Jsdelivr",
	"Consumerinfo.Com", "Brandscreen Pty Ltd",
	"Mythings", "Polar Mobile Group",
	"Answercloud", "Komoona", "Admeta",
	"Meltdsp", "Appier Inc", "Netdna",
	"Budgetedbauer", "Gfk", "Bidtheatre",
	"Research Now", "Undertone Networks",
	"Viglink", "Adbrain", "Adstir", "Sailthru",
	"Vimeo", "Mediametrie", "Livefyre",
	"Mediaforge", "Webklipper", "Tencent",
	"Ib-Ibi",
)

var trackers = combine(mobTrackers, webTrackers)
